### ISSUE TITLE
How to increase the sidebar size?

### ISSUE THREAD

**Issue by BrunoDamacena** [SidebarJS/angular-sidebarjs#3]

**Comment by lorenzodianni** [comment]
You can change the sidebar size with a simple css style

```css
[sidebarjs-container] {
    width: 90%;              /* will be 90% of view */
    max-width: 500px;        /* if 90% width is greater than 500px, stop his size */
}
```
